name: workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libegl1-mesa-dev libxcb-cursor0
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Installing Ruff
      run: |
         pip install ruff
    - name: Running Ruff
      uses: chartboost/ruff-action@v1
    - name: set pythonpath
      run: |
         PWD=$(pwd)
         echo "PYTHONPATH=$PWD/src:$PYTHONPATH" >> $GITHUB_ENV
    - name: Running Unit Tests
      run: |
        cd tests
        python -m unittest discover -v -p "*_test.py"
    - name: Installing Coverage
      run: |
         pip install coverage
    - name: Running Coverage
      run: |
         cd tests
         coverage run -m unittest discover -p "*_test.py"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
